# Dependabot will run on day 7 of each month at 02:21 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 2 7 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 2 7 * *"
    open-pull-requests-limit: 20
    assignees:
      - "klein0r"
    versioning-strategy: "increase"
